[![Open in Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/dlssb/pytorch-exercise/blob/main/numpy.ipynb)

In [ ]:
import numpy as np

### Scalars, Vectors, Matrices, Tensors

In [ ]:
a = np.array(1.)  # scalar
b = np.array([1., 2., 3.])  # vector
c = np.array([[1., 2., 3.],[4., 5., 6.]])  # matrix
d = np.array([[[1., 2., 3.], [4., 5., 6.]], [[7., 8., 9.], [10., 11., 12.]]])  # tensor
e = np.array([[[[1., 2., 3.], [1., 2., 3.]], [[4., 5., 6.], [4., 5., 6.]]],
              [[[7., 8., 9.], [7., 8., 9.]], [[10., 11., 12.], [10., 11., 12.]]]])  # tensor

In [ ]:
print('a:\n', a, sep='')
print('\nb:\n', b, sep='')
print('\nc:\n', c, sep='')
print('\nd:\n', d, sep='')
print('\ne:\n', e, sep='')

a:
1.0

b:
[1. 2. 3.]

c:
[[1. 2. 3.]
 [4. 5. 6.]]

d:
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]

e:
[[[[ 1.  2.  3.]
   [ 1.  2.  3.]]

  [[ 4.  5.  6.]
   [ 4.  5.  6.]]]


 [[[ 7.  8.  9.]
   [ 7.  8.  9.]]

  [[10. 11. 12.]
   [10. 11. 12.]]]]


In [ ]:
print('a.ndim:\n', a.ndim, sep='')
print('\nb.ndim:\n', b.ndim, sep='')
print('\nc.ndim:\n', c.ndim, sep='')
print('\nd.ndim:\n', d.ndim, sep='')
print('\ne.ndim:\n', e.ndim, sep='')

a.ndim:
0

b.ndim:
1

c.ndim:
2

d.ndim:
3

e.ndim:
4


In [ ]:
print('a.shape:\n', a.shape, sep='')
print('\nb.shape:\n', b.shape, sep='')
print('\nc.shape:\n', c.shape, sep='')
print('\nd.shape:\n', d.shape, sep='')
print('\ne.shape:\n', e.shape, sep='')

# print(a.size()) -> error

a.shape:
()

b.shape:
(3,)

c.shape:
(2, 3)

d.shape:
(2, 2, 3)

e.shape:
(2, 2, 2, 3)


In [ ]:
### Quiz: What is the shape of [[[1], [2], [3]], [[4], [5], [6]]]?
### Ans: (2, 3, 1)
q = np.array([[[1], [2], [3]], [[4], [5], [6]]])
print('q.shape:\n', q.shape, sep='')

q.shape:
(2, 3, 1)


### Defining numpy arrays

In [ ]:
a = np.ones(10)
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
a = np.zeros((2, 4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
a = np.full((2,5), 5)
print(a)

[[5 5 5 5 5]
 [5 5 5 5 5]]


In [ ]:
a = np.random.random((2, 3, 4))
print(a)

[[[0.59332948 0.19752868 0.41709429 0.04720721]
  [0.77718583 0.01957468 0.38142667 0.90818823]
  [0.89601647 0.45738142 0.21589344 0.87350824]]

 [[0.28468106 0.28706668 0.85102684 0.63956809]
  [0.84408084 0.61097707 0.17632782 0.35299188]
  [0.46552039 0.3057879  0.4924139  0.32726743]]]


In [ ]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
a = np.arange(10).astype('float')
print(a)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [ ]:
a = np.arange(10).reshape((2,5))
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
### Quiz: Create a 4-by-3-by-2 tensor filled with 0.0 to 23.0
q = np.arange(24).astype('float').reshape((4, 3, 2))
print('q.shape:\n', q.shape, sep='')
print('\n', end='')
print('q:\n', q, sep='')

q.shape:
(4, 3, 2)

q:
[[[ 0.  1.]
  [ 2.  3.]
  [ 4.  5.]]

 [[ 6.  7.]
  [ 8.  9.]
  [10. 11.]]

 [[12. 13.]
  [14. 15.]
  [16. 17.]]

 [[18. 19.]
  [20. 21.]
  [22. 23.]]]


### Indexing & Slicing

In [ ]:
a = np.arange(10)
print("a:\n", a, sep='')

print("\na[0]:\n", a[0], sep='')
print("\na[-1]:\n", a[-1], sep='')
print("\na[-3]:\n", a[-3], sep='')

print("\na[0:10]:\n", a[0:10], sep='')
print("\na[0:]:\n", a[0:], sep='')
print("\na[:10]:\n", a[:10], sep='')
print("\na[:]:\n", a[:], sep='')
print("\na[-4:]:\n", a[-4:], sep='')
print("\na[-8:]:\n", a[-8:], sep='')
print("\na[0:10:2]:\n", a[0:10:2], sep='')
print("\na[2:6:3]:\n", a[2:6:3], sep='')
print("\na[::-1]:\n", a[::-1], sep='')
print("\na[8:5:-1]:\n", a[8:5:-1], sep='')
print("\na[8:5]:\n", a[8:5], sep='')

a:
[0 1 2 3 4 5 6 7 8 9]

a[0]:
0

a[-1]:
9

a[-3]:
7

a[0:10]:
[0 1 2 3 4 5 6 7 8 9]

a[0:]:
[0 1 2 3 4 5 6 7 8 9]

a[:10]:
[0 1 2 3 4 5 6 7 8 9]

a[:]:
[0 1 2 3 4 5 6 7 8 9]

a[-4:]:
[6 7 8 9]

a[-8:]:
[2 3 4 5 6 7 8 9]

a[0:10:2]:
[0 2 4 6 8]

a[2:6:3]:
[2 5]

a[::-1]:
[9 8 7 6 5 4 3 2 1 0]

a[8:5:-1]:
[8 7 6]

a[8:5]:
[]


In [ ]:
### Quiz: Create [9, 6, 3] using a.
print(a[:0:-3])

[9 6 3]


In [ ]:
a = np.arange(9).reshape((3, 3))

print("a:\n", a, sep='')

print("\na[0][0]:\n", a[0][0], sep='')
print("\na[0, 0]:\n", a[0, 0], sep='')
print("\na[1, 1]:\n", a[1, 1], sep='')

a:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

a[0][0]:
0

a[0, 0]:
0

a[1, 1]:
4


In [ ]:
### Quiz: How to access the last row?
print('a[-1]\n', a[-1], sep='')

### Quiz: How to access the second column?
print('\na[:,1]:\n', a[:, 1], sep='')

### Quiz: How to create [8, 5] using a?
print('\na[1:, -1][::-1]:\n', a[1:,-1][::-1], sep='')

a[-1]
[6 7 8]

a[:,1]:
[1 4 7]

a[1:, -1][::-1]:
[8 5]


In [ ]:
a = np.arange(4*3*2).reshape((4, 3, 2))

print("a:\n", a, sep='')
print('\n', end='')
print('a[2, 1, 0]:\n', a[2, 1, 0], sep='')

a:
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]

a[2, 1, 0]:
14


In [ ]:
### Quiz: What would be a[0]?
print(a[0])
print('\n', end='')

### Quiz: What would be a[0, 1]?
print(a[0, 1])
print('\n', end='')

### Quiz: Create [[0, 2, 4], [6, 8, 10]]
print(a[:2, :, 0])

[[0 1]
 [2 3]
 [4 5]]

[2 3]

[[ 0  2  4]
 [ 6  8 10]]


In [ ]:
# Conditional indexing
a = np.arange(3*2).reshape((3, 2))
print('a:\n', a, sep='')

idx = (a%2 == 0)
# idx: [[ True False]
#       [ True False]
#       [ True False]]

print('\na[idx]:\n',a[idx], sep='')

a:
[[0 1]
 [2 3]
 [4 5]]

a[idx]:
[0 2 4]


In [ ]:
### Quiz: How would you create [3, 4, 5] using a?
idx = (a >= 3)

print('a[idx]:\n', a[idx], sep='')

a[idx]:
[3 4 5]


In [ ]:
# Taking specific elements
a = np.arange(10)
idx = [0, 2, 3]
print('a[idx]:\n', a[idx], sep='')
print('\n', end='')

a = np.arange(24).reshape((6, 4))
print('a:\n', a, sep='')
print('\n', end='')

print('a[:, [0, 2, 3]]:\n', a[:, [0, 2, 3]], sep='')
print('\n', end='')

print('a[[0, 2, 3], :]:\n', a[[0, 2, 3], :], sep='')
print('\n', end='')

# Tuple indexing
idx = ((0,0,1,5), (1,2,0,3))
print('a[idx]:\n', a[idx], sep='')
print('\n', end='')

# Ndarray indexing
idx = np.array([[0, 0, 1, 5], [1, 2, 0, 3]])
print('a[idx]:\n', a[idx], sep='')


a[idx]:
[0 2 3]

a:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

a[:, [0, 2, 3]]:
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]
 [12 14 15]
 [16 18 19]
 [20 22 23]]

a[[0, 2, 3], :]:
[[ 0  1  2  3]
 [ 8  9 10 11]
 [12 13 14 15]]

a[idx]:
[ 1  2  4 23]

a[idx]:
[[[ 0  1  2  3]
  [ 0  1  2  3]
  [ 4  5  6  7]
  [20 21 22 23]]

 [[ 4  5  6  7]
  [ 8  9 10 11]
  [ 0  1  2  3]
  [12 13 14 15]]]


In [ ]:
# Three dots indexing (Ellipsis)
a = np.arange(2*3*2*2*4*3).reshape((2,3,2,2,4,-1))

print(a[1, :, :, :, :, 2] == a[1, ..., 2])

[[[[ True  True  True  True]
   [ True  True  True  True]]

  [[ True  True  True  True]
   [ True  True  True  True]]]


 [[[ True  True  True  True]
   [ True  True  True  True]]

  [[ True  True  True  True]
   [ True  True  True  True]]]


 [[[ True  True  True  True]
   [ True  True  True  True]]

  [[ True  True  True  True]
   [ True  True  True  True]]]]


### Math Operations

In [ ]:
# Unary operations
a = np.arange(6).reshape((3, 2))

print('a.sum():\n', a.sum(), sep='')
print('\na.sum(axis=0):\n', a.sum(axis=0), sep='')
print('\na.sum(axis=1):\n', a.sum(axis=1), sep='')

print('\na.mean():\n', a.mean(), sep='')
print('\na.max():\n', a.max(), sep='')
print('\na.min():\n', a.min(), sep='')


a.sum():
15

a.sum(axis=0):
[6 9]

a.sum(axis=1):
[1 5 9]

a.mean():
2.5

a.max():
5

a.min():
0


In [ ]:
### Quiz: Given a = np.arange(24).reshape((2,3,4)),
### what is the mean of the sum w.r.t to the last dimension?
a = np.arange(24).reshape((2, 3, 4))
print('a:\n', a, sep='')
print('\n', end='')
print('a.sum(axis=-1).mean():\n', a.sum(axis=-1).mean(), sep='')


a:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

a.sum(axis=-1).mean():
46.0


In [ ]:
# Vector dot product
a = np.arange(3).astype('float')
b = np.ones(3)

print('np.dot(a, b):\n', np.dot(a, b), sep='')

np.dot(a, b):
3.0


In [ ]:
# Matrix dot product, matrix multiplication
a = np.arange(6).reshape((3, 2))
b = np.ones((2, 3))

print('np.dot(a, b):\n', np.dot(a, b), sep='')
print('\n', end='')

print('a @ b:\n', a @ b, sep='')

np.dot(a, b):
[[1. 1. 1.]
 [5. 5. 5.]
 [9. 9. 9.]]

a @ b:
[[1. 1. 1.]
 [5. 5. 5.]
 [9. 9. 9.]]


In [ ]:
# Tensor dot product, tensor multiplication
a = np.arange(24).reshape((4, 3, 2))
b = np.ones((4, 2, 3))

print('np.dot(a, b).shape:\n', np.dot(a, b).shape, sep='')
print('\n', end='')

print('np.dot(a, b):\n', np.dot(a, b), sep='')
print('\n', end='')

print('(a @ b).shape:\n', (a @ b).shape, sep='')  # Use @ instead of np.dot for tensor multiplication. Then you can interpret the first dimension of the tensors as batch size.
print('\n', end='')

print('a @ b:\n', a @ b, sep='')

np.dot(a, b).shape:
(4, 3, 4, 3)

np.dot(a, b):
[[[[ 1.  1.  1.]
   [ 1.  1.  1.]
   [ 1.  1.  1.]
   [ 1.  1.  1.]]

  [[ 5.  5.  5.]
   [ 5.  5.  5.]
   [ 5.  5.  5.]
   [ 5.  5.  5.]]

  [[ 9.  9.  9.]
   [ 9.  9.  9.]
   [ 9.  9.  9.]
   [ 9.  9.  9.]]]


 [[[13. 13. 13.]
   [13. 13. 13.]
   [13. 13. 13.]
   [13. 13. 13.]]

  [[17. 17. 17.]
   [17. 17. 17.]
   [17. 17. 17.]
   [17. 17. 17.]]

  [[21. 21. 21.]
   [21. 21. 21.]
   [21. 21. 21.]
   [21. 21. 21.]]]


 [[[25. 25. 25.]
   [25. 25. 25.]
   [25. 25. 25.]
   [25. 25. 25.]]

  [[29. 29. 29.]
   [29. 29. 29.]
   [29. 29. 29.]
   [29. 29. 29.]]

  [[33. 33. 33.]
   [33. 33. 33.]
   [33. 33. 33.]
   [33. 33. 33.]]]


 [[[37. 37. 37.]
   [37. 37. 37.]
   [37. 37. 37.]
   [37. 37. 37.]]

  [[41. 41. 41.]
   [41. 41. 41.]
   [41. 41. 41.]
   [41. 41. 41.]]

  [[45. 45. 45.]
   [45. 45. 45.]
   [45. 45. 45.]
   [45. 45. 45.]]]]

(a @ b).shape:
(4, 3, 3)

a @ b:
[[[ 1.  1.  1.]
  [ 5.  5.  5.]
  [ 9.  9.  9.]]

 [[13. 13. 13.]
  [17

In [ ]:
### Quiz: what would happen if a.shape==(4,3,2) and b.shape==(2,3)?
### Ans: The results are same.
a = np.arange(24).reshape((4, 3, 2))
b = np.ones((2, 3))

print('np.dot(a, b).shape:\n', np.dot(a, b).shape, sep='')
print('\n', end='')

print('np.dot(a, b):\n', np.dot(a, b), sep='')
print('\n', end='')

print('(a @ b).shape:\n', (a @ b).shape, sep='')
print('\n', end='')

print('a @ b:\n', a @ b, sep='')

np.dot(a, b).shape:
(4, 3, 3)

np.dot(a, b):
[[[ 1.  1.  1.]
  [ 5.  5.  5.]
  [ 9.  9.  9.]]

 [[13. 13. 13.]
  [17. 17. 17.]
  [21. 21. 21.]]

 [[25. 25. 25.]
  [29. 29. 29.]
  [33. 33. 33.]]

 [[37. 37. 37.]
  [41. 41. 41.]
  [45. 45. 45.]]]

(a @ b).shape:
(4, 3, 3)

a @ b:
[[[ 1.  1.  1.]
  [ 5.  5.  5.]
  [ 9.  9.  9.]]

 [[13. 13. 13.]
  [17. 17. 17.]
  [21. 21. 21.]]

 [[25. 25. 25.]
  [29. 29. 29.]
  [33. 33. 33.]]

 [[37. 37. 37.]
  [41. 41. 41.]
  [45. 45. 45.]]]


### Shape Manipulation

In [ ]:
# Reshapes
a = np.arange(24).reshape((2, 3, 4))

b = a.reshape((6, -1))

print('b:\n', b, sep='')
print('\n', end='')

c = a.reshape((6, 4, -1))
print('c:\n', c, sep='')


b:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

c:
[[[ 0]
  [ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]
  [ 7]]

 [[ 8]
  [ 9]
  [10]
  [11]]

 [[12]
  [13]
  [14]
  [15]]

 [[16]
  [17]
  [18]
  [19]]

 [[20]
  [21]
  [22]
  [23]]]


In [ ]:
# Adding an extra dimension
a = np.arange(3)

print('a:\n', a, sep='')
print('\n', end='')

print('a[:, None]:\n', a[:, None], sep='')

a:
[0 1 2]

a[:, None]:
[[0]
 [1]
 [2]]


In [ ]:
### Quiz: How to make a = np.ones((3,4)) into shape (3, 1, 1, 4) using reshape and None?
a = np.ones((3, 4))
print('a.reshape((3, 1, 1, 4)).shape:\n', a.reshape((3, 1, 1, 4)).shape, sep='')
print('\na[:, None, None, :].shape\n', a[:, None, None, :].shape, sep='')

a.reshape((3, 1, 1, 4)).shape:
(3, 1, 1, 4)

a[:, None, None, :].shape
(3, 1, 1, 4)


In [ ]:
# Stack, concatenation
a = np.ones((3, 2))
b = np.zeros((3, 2))

print('np.vstack([a ,b]):\n', np.vstack([a ,b]), sep='')
print('\n', sep='')

print('np.hstack([a ,b]):\n', np.hstack([a ,b]), sep='')
print('\n', sep='')

print('np.hstack([a ,b, a]):\n', np.hstack([a ,b, a]), sep='')
print('\n', sep='')

# Recommend using np.concatenate on tensors instead of np.vstack and np.hstack,
print('np.concatenate([a, b], axis=0):\n', np.concatenate([a, b], axis=0), sep='')
print('\n', sep='')

print('np.concatenate([a, b], axis=1):\n', np.concatenate([a, b], axis=1), sep='')

np.vstack([a ,b]):
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


np.hstack([a ,b]):
[[1. 1. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 0. 0.]]


np.hstack([a ,b, a]):
[[1. 1. 0. 0. 1. 1.]
 [1. 1. 0. 0. 1. 1.]
 [1. 1. 0. 0. 1. 1.]]


np.concatenate([a, b], axis=0):
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


np.concatenate([a, b], axis=1):
[[1. 1. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 0. 0.]]


In [ ]:
### Quiz: Would concatenating two tensors whose shapes are (4, 3, 2) and (5, 4, 2) on axis=2 work?
### Ans: No

a = np.ones((4, 3, 2))
b = np.zeros((5, 4, 2))

# c = np.concatenate([a, b], axis=2) -> error
# print('c:\n', c.shape, sep='')

In [ ]:
# Matrix transpose
a = np.arange(6).reshape((3, 2))

print('a.T.shape:\n', a.T.shape, sep='')

a.T.shape:
(2, 3)


In [ ]:
# Tensor transpose
a = np.arange(24).reshape((4, 3, 2))

b = np.transpose(a, [0, 2, 1])
print('b.shape:\n', b.shape, sep='')
print('\n', end='')

c = np.transpose(a, [1, 0, 2])
print('c.shape:\n', c.shape, sep='')

b.shape:
(4, 2, 3)

c.shape:
(3, 4, 2)


### Broadcasting

In [ ]:
a = np.arange(6).reshape((3,2))
b = np.arange(2).reshape(2) + 1

print('a:\n', a, sep='')
print('\n', end='')

print('b:\n', b, sep='')
print('\n', end='')

print('a+b:\n', a+b, sep='')

a:
[[0 1]
 [2 3]
 [4 5]]

b:
[1 2]

a+b:
[[1 3]
 [3 5]
 [5 7]]


In [ ]:
### Quiz: What would happen if b were np.arange(2).reshape((2, 1))? How about np.arange(2).reshape((1, 2))?
a = np.arange(6).reshape((3,2))
b = np.arange(2).reshape((2, 1)) + 1

print('a:\n', a, sep='')
print('\n', end='')

print('b:\n', b, sep='')
print('\n', end='')

# print(a+b) -> error

a = np.arange(6).reshape((3,2))
b = np.arange(2).reshape((1, 2)) + 1

print('a:\n', a, sep='')
print('\n', end='')

print('b:\n', b, sep='')
print('\n', end='')

print('a+b:\n', a+b, sep='')

a:
[[0 1]
 [2 3]
 [4 5]]

b:
[[1]
 [2]]

a:
[[0 1]
 [2 3]
 [4 5]]

b:
[[1 2]]

a+b:
[[1 3]
 [3 5]
 [5 7]]


In [ ]:
a = np.arange(12).reshape((2,3,2))
b = np.arange(6).reshape((3,2))

print('a:\n', a, sep='')
print('\n', end='')

print('b:\n', b, sep='')
print('\n', end='')

print('a+b:\n', a+b, sep='')

a:
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]

b:
[[0 1]
 [2 3]
 [4 5]]

a+b:
[[[ 0  2]
  [ 4  6]
  [ 8 10]]

 [[ 6  8]
  [10 12]
  [14 16]]]


In [ ]:
### Quiz: How can we use None to do a+b?
a = np.arange(12).reshape((2,3,2))
b = np.arange(6).reshape((3,2))[None, : ,:]

print('a:\n', a, sep='')
print('\n', end='')

print('b:\n', b, sep='')
print('\n', end='')

print('a+b:\n', a+b, sep='')

a:
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]

b:
[[[0 1]
  [2 3]
  [4 5]]]

a+b:
[[[ 0  2]
  [ 4  6]
  [ 8 10]]

 [[ 6  8]
  [10 12]
  [14 16]]]


### Final Quiz

In [ ]:
def sigmoid(x):
    return 1./(1. + np.exp(-x))

# Define a function that, given M of shape (m,n) and W of shape (4n, n), executes the following:
# - Take the first half rows of M
# - Take the second half rows of M
# - Take the odd-numbered rows of M
# - Take the even-numbered rows of M
# - Append them horizontally in the listed order so that you obtain a matrix X of shape (?, 4n)
# - Linearly transform X with W so that you obtain a matrix Y of shape (?, ?)
# - Put Y through the sigmoid function
# - Obtain the sum of the row-wise mean

def foo(M, W):
    r = int(M.shape[0]/2)
    fh = M[:r]
    sh = M[r:]
    on = M[1::2]
    en = M[0::2]
    X = np.concatenate([fh, sh, on, en], axis=1)
    Y = X @ W
    n = sigmoid(Y)
    result = np.mean(n, axis=0).sum()
    return result

M = (np.arange(20).reshape((10,2)).astype('float') - 10.) / 10
W = np.arange(16).reshape(8,2).astype('float') / 10.

print('answer:\n', foo(M, W), sep='')

answer:
1.0114933115231504
